name: FTP Deploy

on:
  push:
    branches:
      - main  # lub inna gałąź, której używasz

jobs:
  ftp-deploy:
    name: Deploy to FTP
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repo
      uses: actions/checkout@v3

    - name: FTP Deploy
      uses: SamKirkland/FTP-Deploy-Action@v4.3.4
      with:
        server: ftp.server115683.nazwa.pl
        username: server115683_master
        password: HatingNiggersFest911
        server-dir: /testrepo
